name: Performance Benchmarks

on:
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Run Benchmarks
      run: cargo bench --bench init-time > res_init.txt
      run: cargo bench --bench load-time > res_read.txt
      run: cargo bench --bench store-time > res_write.txt

    - name: Post Benchmark Results as PR Comment
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const initResults = fs.readFileSync('res_init.txt', 'utf8');
          const readResults = fs.readFileSync('res_read.txt', 'utf8');
          const writeResults = fs.readFileSync('res_write.txt', 'utf8');

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 📊 Benchmark Results

### Init times

\`\`\`
${initResults}
\`\`\`

### Read times

\`\`\`
${readResults}
\`\`\`

### Write times

\`\`\`
${writeResults}
\`\`\`

*automated report*`
          });
