name: Publish Crate

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Publish main crate
        run: cargo publish --package fast-stm --token ${CIO_TOKEN}
        env:
          CIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
