name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Check Format
        run: cargo fmt -- --check
  clippy:
    name: Check `${{ matrix.backend }}` clippy lints (${{ matrix.feats }})
    strategy:
      matrix:
        backend: [ fast-stm, sserp-stm ]
        feats: [ --all-features, --no-default-features ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run Clippy
        run: cargo clippy -p ${{ matrix.backend }} --all-targets ${{ matrix.feats }}
  tests:
    name: Run `${{ matrix.backend }}` tests (${{ matrix.feats }})
    strategy:
      matrix:
        backend: [ fast-stm, sserp-stm ]
        feats: [ --all-features, --no-default-features ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run Tests
        run: cargo test -p ${{ matrix.backend }} --all-targets ${{ matrix.feats }}
